- hosts: all
  user: root
  sudo: yes
  tasks:
    - name: set hostname
      hostname:
        name: nas

    - name: set timezone
      timezone:
        name: Asia/Tokyo

    - name: snap installs
      snap:
        name:
          - tree

    - name: apt installs
      apt:
        name:
          - zsh
          - ntpdate
        update_cache: true

    - name: add cron time
      cron:
        name: "時間修正"
        minute: "5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "ntpdate ntp.nict.jp"
        state: present

    - name: create user
      user:
        name: mfmf
        shell: /bin/zsh
