- hosts: all
  user: ubuntu
  tasks:
    - name: set hostname
      become: true
      hostname:
        name: nas

    - name: set timezone
      become: true
      timezone:
        name: Asia/Tokyo

    - name: snap installs
      become: true
      snap:
        name:
          - tree

    - name: apt installs
      become: true
      apt:
        name:
          - zsh
          - ntpdate

    - name: add cron time
      become: true
      cron:
        name: "時間修正"
        minute: "5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: "ntpdate ntp.nict.jp"
        state: present
