---
- hosts: nas

  vars:
    host_name: "nas"
  roles:
    - ../core
  tasks:
    - name: create user
      user:
        name: nas
        shell: /bin/bash

    - name: apt installs
      apt:
        name:
          - samba
        update_cache: true

    - name: samba config
      lineinfile:
        path: /etc/samba/smb.conf
        create: yes
        line: "{{ item }}"
      with_items:
        - "[nas]"
        - "  comment = Sample Share"
        - "  path = /home/nas"
        - "  public = yes"
        - "  writable = yes"
        - "  guest ok = yes"
        - "  guest only = yes"
        - "  force user = nas"

    - name: mkdir /mnt/nas
      file:
        path: /mnt/nas
        state: directory

    - name: mount device
      mount:
        name: /mnt/nas
        src: /dev/sda
        fstype: ext4
        opts: defaults
        state: mounted

    - name: auto start smbd
      service:
        name: smbd
        enabled: yes
        state: started
