- name: set hostname
  hostname:
    name: "{{ host_name }}"

- name: set timezone
  timezone:
    name: Asia/Tokyo

- name: snap installs
  snap:
    name:
      - tree

- name: apt installs
  apt:
    name:
      - ntpdate
    update_cache: true

- name: add cron time
  cron:
    name: "時間修正"
    minute: "5"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "ntpdate ntp.nict.jp"
    state: present

- name: create user
  user:
    name: mfmf
    shell: /bin/bash

- name: non password sudo
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: 'mfmf ALL=(ALL) NOPASSWD: ALL'

- name: mkdir /home/mfmf/.ssh
  file:
    path: /home/mfmf/.ssh
    state: directory
    owner: mfmf
    group: mfmf
    mode: 0700

- name: add pub key
  copy:
    src: template/authorized_keys.j2
    dest: /home/mfmf/.ssh/authorized_keys
    owner: mfmf
    group: mfmf
    mode: 0600
    backup: no
